### ISSUE TITLE
API description

### ISSUE THREAD

**Issue by JungHY** [microsoft/AirSim-NeurIPS2019-Drone-Racing#103]
there are lots of parameters of functions in API doc

some of them are explained as "Description"

what does "Description" mean?

I cannot find parameters' exact explain in the doc
like timeout_sec, drivetrain, lookahead of moveToPositionAsync function

**Comment by madratman** [comment]
Hey @JungHY. "description" is the default string generated by the auto-doc utility we were using. 
Apologies, yes, some of the APIs are not completely documented. 
see this page for explanation of drivetrain, lookahead, and adaptive_lookahead in moveToPositionAsync - https://microsoft.github.io/AirSim/docs/apis/ 
timeout_sec means that the function stops execution after "timeout_sec" seconds have passed.
