### ISSUE TITLE
How can I run the log_monitor.py?

### ISSUE THREAD

**Issue by surfii3z** [microsoft/AirSim-NeurIPS2019-Drone-Racing#117]
So what I did is
`~/AirSim_Training $ ./AirSimExe.sh -windowed -opengl4`
Then I run log_monitor.py in 
`~/AirSim_Training/AirSimExe/Saved/Logs$ python3.7 log_monitor.py`
Then I run baseline_racer.py in
`~/AirSim-NeurIPS2019-Drone-Racing/baselines$ python3.7 baseline_racer.py`
I got this error

> ERROR Bad line: [2019.11.09-15.02.11:244][652]LogAudioMixer: Display: No commands were queued while flushing the source manager.
> 
> Tokens: ['[2019.11.09-15.02.11:244][652]LogAudioMixer:', 'Display:', 'No', 'commands', 'were', 'queued', 'while', 'flushing', 'the', 'source', 'manager.']
> ERROR Bad line: [2019.11.09-15.02.11:273][652]LogSlate: Request Window 'AirSimExe (64-bit Development GLSL_430) ' being destroyed
> 
> Tokens: ['[2019.11.09-15.02.11:273][652]LogSlate:', 'Request', 'Window', "'AirSimExe", '(64-bit', 'Development', 'GLSL_430)', "'", 'being', 'destroyed']
> ERROR Bad line: [2019.11.09-15.02.11:321][652]LogSlate: Window 'AirSimExe (64-bit Development GLSL_430) ' being destroyed
> 
> Tokens: ['[2019.11.09-15.02.11:321][652]LogSlate:', 'Window', "'AirSimExe", '(64-bit', 'Development', 'GLSL_430)', "'", 'being', 'destroyed']
> ERROR Bad line: [2019.11.09-15.02.11:324][652]LogSlate: Slate User Destroyed.  User Index 0, Is Virtual User: 0
> 
> Tokens: ['[2019.11.09-15.02.11:324][652]LogSlate:', 'Slate', 'User', 'Destroyed.', 'User', 'Index', '0,', 'Is', 'Virtual', 'User:', '0']
> ERROR Bad line: [2019.11.09-15.02.11:324][652]LogExit: Preparing to exit.
> 
> Tokens: ['[2019.11.09-15.02.11:324][652]LogExit:', 'Preparing', 'to', 'exit.']
> ERROR Bad line: [2019.11.09-15.02.11:327][652]LogSlate: Updating window title bar state: overlay mode, drag disabled, window buttons hidden, title bar hidden
> 
> Tokens: ['[2019.11.09-15.02.11:327][652]LogSlate:', 'Updating', 'window', 'title', 'bar', 'state:', 'overlay', 'mode,', 'drag', 'disabled,', 'window', 'buttons', 'hidden,', 'title', 'bar', 'hidden']
> ERROR Bad line: [2019.11.09-15.02.11:412][652]LogRendererCore: FGlobalReadBuffer::ReleaseRHI
> 
> Tokens: ['[2019.11.09-15.02.11:412][652]LogRendererCore:', 'FGlobalReadBuffer::ReleaseRHI']
> ERROR Bad line: [2019.11.09-15.02.11:412][652]LogRendererCore: FGlobalDynamicReadBuffer::Cleanup()
> 
> Tokens: ['[2019.11.09-15.02.11:412][652]LogRendererCore:', 'FGlobalDynamicReadBuffer::Cleanup()']
> ERROR Bad line: [2019.11.09-15.02.11:412][652]LogRendererCore: FGlobalReadBuffer::ReleaseRHI
> 
> Tokens: ['[2019.11.09-15.02.11:412][652]LogRendererCore:', 'FGlobalReadBuffer::ReleaseRHI']
> ERROR Bad line: [2019.11.09-15.02.11:412][652]LogRendererCore: FGlobalDynamicReadBuffer::Cleanup()
> 
> Tokens: ['[2019.11.09-15.02.11:412][652]LogRendererCore:', 'FGlobalDynamicReadBuffer::Cleanup()']
> ERROR Bad line: [2019.11.09-15.02.11:412][652]LogRendererCore: FGlobalReadBuffer::ReleaseRHI
> 
> Tokens: ['[2019.11.09-15.02.11:412][652]LogRendererCore:', 'FGlobalReadBuffer::ReleaseRHI']
> ERROR Bad line: [2019.11.09-15.02.11:412][652]LogRendererCore: FGlobalDynamicReadBuffer::Cleanup()
> 
> Tokens: ['[2019.11.09-15.02.11:412][652]LogRendererCore:', 'FGlobalDynamicReadBuffer::Cleanup()']
> ERROR Bad line: [2019.11.09-15.02.11:457][652]LogModuleManager: Shutting down and abandoning module AutomationController (194)
> 
> Tokens: ['[2019.11.09-15.02.11:457][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'AutomationController', '(194)']
> ERROR Bad line: [2019.11.09-15.02.11:457][652]LogModuleManager: Shutting down and abandoning module AutomationWorker (192)
> 
> Tokens: ['[2019.11.09-15.02.11:457][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'AutomationWorker', '(192)']
> ERROR Bad line: [2019.11.09-15.02.11:457][652]LogModuleManager: Shutting down and abandoning module Voice (190)
> 
> Tokens: ['[2019.11.09-15.02.11:457][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'Voice', '(190)']
> ERROR Bad line: [2019.11.09-15.02.11:457][652]LogModuleManager: Shutting down and abandoning module AIModule (188)
> 
> Tokens: ['[2019.11.09-15.02.11:457][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'AIModule', '(188)']
> ERROR Bad line: [2019.11.09-15.02.11:457][652]LogModuleManager: Shutting down and abandoning module GameplayDebugger (187)
> 
> Tokens: ['[2019.11.09-15.02.11:457][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'GameplayDebugger', '(187)']
> ERROR Bad line: [2019.11.09-15.02.11:457][652]LogModuleManager: Shutting down and abandoning module NavigationSystem (185)
> 
> Tokens: ['[2019.11.09-15.02.11:457][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'NavigationSystem', '(185)']
> ERROR Bad line: [2019.11.09-15.02.11:457][652]LogModuleManager: Shutting down and abandoning module WebMMediaFactory (182)
> 
> Tokens: ['[2019.11.09-15.02.11:457][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'WebMMediaFactory', '(182)']
> ERROR Bad line: [2019.11.09-15.02.11:457][652]LogModuleManager: Shutting down and abandoning module WebMMedia (180)
> 
> Tokens: ['[2019.11.09-15.02.11:457][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'WebMMedia', '(180)']
> ERROR Bad line: [2019.11.09-15.02.11:457][652]LogModuleManager: Shutting down and abandoning module WmfMediaFactory (178)
> 
> Tokens: ['[2019.11.09-15.02.11:457][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'WmfMediaFactory', '(178)']
> ERROR Bad line: [2019.11.09-15.02.11:457][652]LogModuleManager: Shutting down and abandoning module ImgMediaFactory (176)
> 
> Tokens: ['[2019.11.09-15.02.11:457][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'ImgMediaFactory', '(176)']
> ERROR Bad line: [2019.11.09-15.02.11:457][652]LogModuleManager: Shutting down and abandoning module AvfMediaFactory (174)
> 
> Tokens: ['[2019.11.09-15.02.11:457][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'AvfMediaFactory', '(174)']
> ERROR Bad line: [2019.11.09-15.02.11:457][652]LogModuleManager: Shutting down and abandoning module Media (173)
> 
> Tokens: ['[2019.11.09-15.02.11:457][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'Media', '(173)']
> ERROR Bad line: [2019.11.09-15.02.11:462][652]LogModuleManager: Shutting down and abandoning module CharacterAI (170)
> 
> Tokens: ['[2019.11.09-15.02.11:462][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'CharacterAI', '(170)']
> ERROR Bad line: [2019.11.09-15.02.11:462][652]LogModuleManager: Shutting down and abandoning module SessionServices (168)
> 
> Tokens: ['[2019.11.09-15.02.11:462][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'SessionServices', '(168)']
> ERROR Bad line: [2019.11.09-15.02.11:462][652]LogModuleManager: Shutting down and abandoning module LevelSequence (166)
> 
> Tokens: ['[2019.11.09-15.02.11:462][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'LevelSequence', '(166)']
> ERROR Bad line: [2019.11.09-15.02.11:462][652]LogModuleManager: Shutting down and abandoning module MovieSceneTracks (164)
> 
> Tokens: ['[2019.11.09-15.02.11:462][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'MovieSceneTracks', '(164)']
> ERROR Bad line: [2019.11.09-15.02.11:462][652]LogModuleManager: Shutting down and abandoning module MovieScene (162)
> 
> Tokens: ['[2019.11.09-15.02.11:462][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'MovieScene', '(162)']
> ERROR Bad line: [2019.11.09-15.02.11:462][652]LogModuleManager: Shutting down and abandoning module StreamingPauseRendering (160)
> 
> Tokens: ['[2019.11.09-15.02.11:462][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'StreamingPauseRendering', '(160)']
> ERROR Bad line: [2019.11.09-15.02.11:462][652]LogModuleManager: Shutting down and abandoning module ImageWriteQueue (158)
> 
> Tokens: ['[2019.11.09-15.02.11:462][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'ImageWriteQueue', '(158)']
> ERROR Bad line: [2019.11.09-15.02.11:462][652]LogModuleManager: Shutting down and abandoning module ProfilerService (156)
> 
> Tokens: ['[2019.11.09-15.02.11:462][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'ProfilerService', '(156)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module TaskGraph (154)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'TaskGraph', '(154)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module SteamVRController (152)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'SteamVRController', '(152)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module ProceduralMeshComponent (150)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'ProceduralMeshComponent', '(150)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module MobilePatchingUtils (148)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'MobilePatchingUtils', '(148)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module EditableMesh (146)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'EditableMesh', '(146)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module CustomMeshComponent (144)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'CustomMeshComponent', '(144)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module CableComponent (142)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'CableComponent', '(142)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module AudioCapture (140)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'AudioCapture', '(140)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module ArchVisCharacter (138)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'ArchVisCharacter', '(138)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module AndroidPermission (136)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'AndroidPermission', '(136)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module MediaCompositing (134)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'MediaCompositing', '(134)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module LinearTimecode (132)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'LinearTimecode', '(132)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module ImgMedia (130)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'ImgMedia', '(130)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module BackChannel (128)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'BackChannel', '(128)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module AppleVision (126)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'AppleVision', '(126)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module AppleImageUtils (124)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'AppleImageUtils', '(124)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module GeometryCacheTracks (122)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'GeometryCacheTracks', '(122)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module GeometryCache (120)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'GeometryCache', '(120)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module VariantManagerContent (118)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'VariantManagerContent', '(118)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module DroneRacing (116)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'DroneRacing', '(116)']
> ERROR Bad line: [2019.11.09-15.02.11:504][652]LogModuleManager: Shutting down and abandoning module AirSimExe (114)
> 
> Tokens: ['[2019.11.09-15.02.11:504][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'AirSimExe', '(114)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module RuntimePhysXCooking (112)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'RuntimePhysXCooking', '(112)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module LocationServicesBPLibrary (110)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'LocationServicesBPLibrary', '(110)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module ActorSequence (108)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'ActorSequence', '(108)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module UdpMessaging (106)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'UdpMessaging', '(106)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module TcpMessaging (104)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'TcpMessaging', '(104)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module FacialAnimation (102)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'FacialAnimation', '(102)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module SignificanceManager (100)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'SignificanceManager', '(100)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module AnimationSharing (98)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'AnimationSharing', '(98)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module LightPropagationVolumeRuntime (96)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'LightPropagationVolumeRuntime', '(96)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module AISupportModule (94)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'AISupportModule', '(94)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module Paper2D (92)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'Paper2D', '(92)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module PhysXVehicles (90)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'PhysXVehicles', '(90)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module AirSim (88)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'AirSim', '(88)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module WebMMoviePlayer (86)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'WebMMoviePlayer', '(86)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module PacketHandler (84)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'PacketHandler', '(84)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module ClothingSystemRuntime (82)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'ClothingSystemRuntime', '(82)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module MediaAssets (80)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'MediaAssets', '(80)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module Overlay (78)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'Overlay', '(78)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module UMG (76)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'UMG', '(76)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module SlateReflector (74)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'SlateReflector', '(74)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module Slate (72)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'Slate', '(72)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module MRMesh (70)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'MRMesh', '(70)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module Messaging (68)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'Messaging', '(68)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module HeadMountedDisplay (66)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'HeadMountedDisplay', '(66)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module AudioMixerSDL (64)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'AudioMixerSDL', '(64)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module Networking (62)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'Networking', '(62)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module Core (60)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'Core', '(60)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module ImageWrapper (56)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'ImageWrapper', '(56)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module OpenGLDrv (54)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'OpenGLDrv', '(54)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module InputCore (52)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'InputCore', '(52)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module PhysXCooking (50)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'PhysXCooking', '(50)']
> ERROR Bad line: [2019.11.09-15.02.11:505][652]LogModuleManager: Shutting down and abandoning module SteamVR (48)
> 
> Tokens: ['[2019.11.09-15.02.11:505][652]LogModuleManager:', 'Shutting', 'down', 'and', 'abandoning', 'module', 'SteamVR', '(48)']
> Traceback (most recent call last):
>   File "log_monitor.py", line 62, in <module>
>     main() 
>   File "log_monitor.py", line 59, in main
>     process(line)
>   File "log_monitor.py", line 31, in process
>     if tokens[3] == "disqualified" and tokens[4] == '1' and tokens[0] not in disqualified_racers:
> IndexError: list index out of range

I expected to use the information to keep track that what is the next gate that "drone_1" needs to pass through in tier2. Is it possible to do this?

**Comment by madratman** [comment]
Run the baseline_racer.py first, then log_monitor.py. 
The call to start_race() starts the call to the server side log file generator.

**Comment by surfii3z** [comment]
Thank you so much. Does the log information e.g. drone_1 pass gate 2 allow in Qualification?

**Comment by madratman** [comment]
Yes, you can use it. You can also do something like https://github.com/microsoft/AirSim-NeurIPS2019-Drone-Racing/issues/79#issuecomment-541883689
