### ISSUE TITLE
Question: simGetGroundTruthKinematics

### ISSUE THREAD

**Issue by yannbouteiller** [microsoft/AirSim-NeurIPS2019-Drone-Racing#119]
Hello,

Is simGetGroundTruthKinematics() authorized? If yes, in which tier/for which drones?

**Comment by madratman** [comment]
Yes, it is allowed in all tiers for all drones. The output should be same as simGetMultirotorState

**Comment by yannbouteiller** [comment]
But this would give the kinematics of the opponent drone in tier 3?

**Comment by madratman** [comment]
My bad. It is only allowed in tier 1 (both drones), in tier 2 for the only drone_1, and in tier 3 for drone_1 only.
