### ISSUE TITLE
Open .pak files with UE4

### ISSUE THREAD

**Issue by ctoumieh** [microsoft/AirSim-NeurIPS2019-Drone-Racing#12]
Hi,
Is it possible to open the .pak files with Unreal Engine 4 in order to get ground-truth poses of gates and obstacles? I tried UnrealPak and other third party unpackers but they didn't work.
Cheers,
CT

**Comment by madratman** [comment]
Please see my comment here https://github.com/microsoft/AirSim-NeurIPS2019-Drone-Racing/issues/14#issuecomment-516199072
you can do the same with an API call

The pak files can not be opened with UE4
