### ISSUE TITLE
Maximum acceleration of drone

### ISSUE THREAD

**Issue by ctoumieh** [microsoft/AirSim-NeurIPS2019-Drone-Racing#13]
Hi,
While testing moveByAngleThrottle(), it appears that the maximum acceleration of the drone is ~1.7g which is low for a racing drone. Are you planing on modifying it or will it be the same throughout the competition? Or is the drag coefficient too high?
Cheers,
CT

**Comment by yannbouteiller** [comment]
Actually I have been looking for documentation for this function (ranges of parameters values and what they mean exactly) but could not find anything. Is this information available somewhere please?

**Comment by madratman** [comment]
I've updated this API, and added more lower level APIs. 
Please see https://microsoft.github.io/AirSim-NeurIPS2019-Drone-Racing/, and the recent release notes [v0.1.1](https://github.com/microsoft/AirSim-NeurIPS2019-Drone-Racing/releases/tag/v0.1.1-linux) and [v0.1.0](https://github.com/microsoft/AirSim-NeurIPS2019-Drone-Racing/releases/tag/v0.1.0-linux)


re making the drone more agile - we'll start working on this
