### ISSUE TITLE
Deploying AirSim-based simulations on real-world systems (UAVs)

### ISSUE THREAD

**Issue by prabhasak** [microsoft/AirSim-NeurIPS2019-Drone-Racing#140]
Hi all,

As you know, Game of Drones is a simulation-based drone-racing competition built on AirSim. However, there is also an implementation side to it, i.e. deploying an actual drone for the task.

I am currently trying out Imitation Learning methods for UAV landing, in an environment designed on AirSim. The hope is to be able to learn an expert’s maneuver (simulation) and test the learned policy on a drone (implementation).

Has anyone come across such projects, where a learning algorithm was used on an environment specifically built on AirSim, and the learned model was deployed on a real-world system? I am particularly interested in the implementation aspect of it.

Thank you!

**Comment by ugurkanates** [comment]
Yes there is even a paper based on @madanm-microsoft 

https://github.com/microsoft/AirSim-Drone-Racing-VAE-Imitation

Good luck on your work
