### ISSUE TITLE
Guidelines for dev packages include Tensorflow?

### ISSUE THREAD

**Issue by hollygrimm** [microsoft/AirSim-NeurIPS2019-Drone-Racing#15]
Hi,
From the [guidelines](https://github.com/microsoft/AirSim-NeurIPS2019-Drone-Racing/blob/master/docs/competition_guidelines.md):

> The participants are expected to develop everything in Python using typical packages (numpy, scipy, etc.) and the provided AirSim API.

Does this include Tensorflow?

Thanks!

**Comment by madratman** [comment]
Yeah, you can use any python module you wish.
