### ISSUE TITLE
Need to pass -nosound to avoid crash.

### ISSUE THREAD

**Issue by chisophugis** [microsoft/AirSim-NeurIPS2019-Drone-Racing#16]
Seems to be the same issue reported here: https://github.com/carla-simulator/carla/issues/1619
Passing `-nosound` to AirSimExe.sh seems to fix it.

Failure log here: https://gist.github.com/chisophugis/d45d41c68b3e14c419487b2d14b9b4e4

I'm on ubuntu 18.04 with nvidia.

**Comment by madratman** [comment]
Thanks for reporting this. Closing as this is the only occurence of this issue. Will link to your fix if someone else posts is.
