### ISSUE TITLE
Cannot run AirSimExe on Windows 7 with NVIDIA Quadro 400

### ISSUE THREAD

**Issue by Bonum** [microsoft/AirSim-NeurIPS2019-Drone-Racing#2]
Hello,
I tried to run AirSimExe on Windows 7 64 bit with NVIDIA Quadro 400 driver, installed version 340.52. 
I got a warning to upgrade to version 398.36. Unfortunately it was not possible to install this version.
Runnung  AirSimExe I've got the following Assertion error:
Assrtion failed: Resource
[File:D\Build\++UE4\Sync\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11UniformBuffer.cpp] [Line: 257]
Invalid resource entry creating uniform buffer,
FViewUniformShaderParameters.Resources[48],ResourceType 0x6.

and the application crashed.

Is there any way to short-cut this assertion?

**Comment by madratman** [comment]
Win 7 is too old and we're not supporting it. 
Please use Win 10
