### ISSUE TITLE
AirSim Windows Binary won't open (missing nlopt-0.dll)

### ISSUE THREAD

**Issue by mrpropellers** [microsoft/AirSim-NeurIPS2019-Drone-Racing#25]
Attempting to open the AirSim binary on my machine gives the following System Error:
"The code execution cannot proceed because nlopt-0.dll was not found. Reinstalling the program may fix this problem."

Using a RoG Zephyrus gx701 with Windows 10 Pro v1809 and haven't had issues with other UE4 games.

**Comment by madratman** [comment]
I just updated the [AirSim-Windows.zip](https://github.com/microsoft/AirSim-NeurIPS2019-Drone-Racing/releases/tag/v0.1.1-windows) with nlopt-0.dll
We are using that in our trajectory planning backend. 
Please redownload the binary
