### ISSUE TITLE
cancelLastTask() issue

### ISSUE THREAD

**Issue by StanislavSychev** [microsoft/AirSim-NeurIPS2019-Drone-Racing#32]
Hello,

I've got following error using `client.cancelLastTask()` method without any arguments

```
TypeError: cancelLastTask() takes 0 positional arguments but 1 was given
```

I'm using latest v0.1.2 relises

**Comment by madratman** [comment]
fixed with [airsimneurips](https://pypi.org/project/airsimneurips/) v0.1.1, upgrade your pip package. 
Now cancelLastTask takes in a `vehicle_name` argument. 
https://microsoft.github.io/AirSim-NeurIPS2019-Drone-Racing/#airsimneurips.client.MultirotorClient.cancelLastTask
