### ISSUE TITLE
How to save and set the simulator state?

### ISSUE THREAD

**Issue by yannbouteiller** [microsoft/AirSim-NeurIPS2019-Drone-Racing#33]
Hello,

I don't think this is actually possible right now because the closest things I find in the API are getMultirotorState(), getVehiclePose() and setVehiclePose() (I don't think these two last ones allow to save and set kinematics), but it would be useful for some Reinforcement Learning approaches if we could save a previous state and set it back.

Regards,
Yann.

**Comment by madratman** [comment]
Unfortunately, we didn't have the bandwidth to add this feature, as evident. The discounted rewards should nudge your policy to not end up in states which lead to a crash / collision. Or, approaches like Hindsight Experience Replay could be leveraged
