### ISSUE TITLE
Methods Results

### ISSUE THREAD

**Issue by anas-abulehia** [microsoft/AirSim-NeurIPS2019-Drone-Racing#45]
I was trying some methods in documentation but python shell responds Object has no attribute , it seems that it does not exist ?? any solution for that guys.

Thanks in advance

**Comment by madratman** [comment]
Can you please elaborate on the "some methods" part of your question. 
Please share the error msg from the terminal, along with the relevant source code snippet / line

**Comment by anas-abulehia** [comment]
![Capture1](https://user-images.githubusercontent.com/49106882/64062227-bcb1cc80-cbec-11e9-8a61-4e9263336de3.JPG)

**Comment by madratman** [comment]
please update your airsimneurips package. this API is already there 

`pip install airsimneurips --upgrade` or `pip3 install airsimneurips --upgrade`
