### ISSUE TITLE
How to disable log streaming?

### ISSUE THREAD

**Issue by yannbouteiller** [microsoft/AirSim-NeurIPS2019-Drone-Racing#46]
Hello,

How can we disable log streaming please?

**Comment by madratman** [comment]
@ironclownfish we need to have this in the next release, can you update the internal linux branch tomorrow.

**Comment by madratman** [comment]
[simDisableRaceLog](https://microsoft.github.io/AirSim-NeurIPS2019-Drone-Racing/api.html#airsimneurips.client.MultirotorClient.simDisableRaceLog) is here
see release notes - https://github.com/microsoft/AirSim-NeurIPS2019-Drone-Racing/releases/tag/v0.3.0-linux
