### ISSUE TITLE
is it possible to run the game without visulization?

### ISSUE THREAD

**Issue by sezan92** [microsoft/AirSim-NeurIPS2019-Drone-Racing#54]
Hello , is it possible to run the game without visualization? That will be helpful because, in that case i can run the game and codes in the clound environment where i only have access to jupyter notebooks

**Comment by patrickhart** [comment]
You can set a flag before starting AirSim:
```
export SDL_VIDEODRIVER=offscreen && ./AirSimExe.sh --windowed`.
```
However, it still will require you to install the required dependencies in e.g. a Docker image.

**Comment by sezan92** [comment]
thanks. i can install everything in the cloud computer via linux commands..thanks
