### ISSUE TITLE
moveOnSplineAsync is not work

### ISSUE THREAD

**Issue by anas-abulehia** [microsoft/AirSim-NeurIPS2019-Drone-Racing#55]
I created my waypoints to navigate drone from a to b, I command moveOnSplineAsync(waypoints)
but drone did not move at all, please check it and let me know if this profound function is working or not ???

**Comment by madratman** [comment]
Hi @anas-abulehia, the profound function christened `moveOnSpline` does work. 
Please [`baseline_racer.py`](https://github.com/microsoft/AirSim-NeurIPS2019-Drone-Racing/blob/master/baselines/baseline_racer.py) closely
Please ensure that you're calling **all** the functions in [`initialize_drone`](https://github.com/microsoft/AirSim-NeurIPS2019-Drone-Racing/blob/master/baselines/baseline_racer.py#L53) in your script before you call moveOnSpline.

**Comment by madratman** [comment]
We can help debug you of course, if you can share a python snippet.

**Comment by anas-abulehia** [comment]
Yes , I have to define gains I define them as in initialize_drone then client.setTrajectoryTrackerGains(traj_tracker_gains), but it did not work see photo.
![image](https://user-images.githubusercontent.com/49106882/64913843-72822c80-d750-11e9-888e-541e2518bbbc.png)
 Regarding values of these gains shall we tune them or it should take as it? and about maximum velocity and accelerations can we change them or we should take them as in base_line_racer.py

**Comment by anas-abulehia** [comment]
![image](https://user-images.githubusercontent.com/49106882/65186543-8096bc80-da72-11e9-8f6a-921b9c6f97ca.png)
Please help me in this regard
