### ISSUE TITLE
simGetObjectPose() crashes

### ISSUE THREAD

**Issue by yannbouteiller** [microsoft/AirSim-NeurIPS2019-Drone-Racing#66]
Hello,

Since Friday, the simulator has become unusable for me because simGetObjectPose() crashes, and therefore I cannot get the gate poses.

What I get is basically:

> 
> >>> import airsimneurips as airsim
> >>> client = airsim.MultirotorClient()
> >>> client.confirmConnection()
> Connected!
> >>> client.simLoadLevel('Soccer_Field_Easy')
> True
> >>> client.simGetObjectPose('gate_01')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/yann/anaconda3/lib/python3.7/site-packages/airsimneurips/client.py", line 221, in simGetObjectPose
>     pose = self.client.call('simGetObjectPose', object_name)
>   File "/home/yann/anaconda3/lib/python3.7/site-packages/msgpackrpc/session.py", line 41, in call
>     return self.send_request(method, args).get()
>   File "/home/yann/anaconda3/lib/python3.7/site-packages/msgpackrpc/future.py", line 45, in get
>     raise error.RPCError(self._error)
> msgpackrpc.error.RPCError: rpclib: function 'simGetObjectPose' (called with 1 arg(s)) threw an exception. The exception is not derived from std::exception. No further information available.
>

**Comment by madratman** [comment]
@yannbouteiller just pushed 0.2.1 for airsimneurips
apologies for the delay, didn't get time over the weekend.
