### ISSUE TITLE
What is 't_c' in the competition guidelines?

### ISSUE THREAD

**Issue by yannbouteiller** [microsoft/AirSim-NeurIPS2019-Drone-Racing#75]
Hello,

In the competition guidelines, there is a table with:

t_c : Time penalty incurred by chasing drone for colliding with leading drone | 3 seconds

Since the chasing drone is disqualified in the event of a drone-drone collision, what is t_c please?

**Comment by madratman** [comment]
You're right. That t_c should not be there, as the chaser is disqualified. We'll remove it
