### ISSUE TITLE
Is it possible to use C++ API and C++ code for competition or Python only?

### ISSUE THREAD

**Issue by frontw** [microsoft/AirSim-NeurIPS2019-Drone-Racing#8]
Is it possible to use C++ API and C++ code for competition or Python only?

**Comment by madratman** [comment]
Only python

**Comment by ctoumieh** [comment]
Hi,
There are important libraries that have only a Matlab or C++ interface. I know it's a bit of a grey area, but is it within the rules to write a python script that communicates with our Matlab/C++ interface to access these libraries?
Cheers,
CT
