### ISSUE TITLE
Can I use other libraries?

### ISSUE THREAD

**Issue by JungHY** [microsoft/AirSim-NeurIPS2019-Drone-Racing#93]
when race on tier2 or tier3
api gives only approximate position of gates so i'm gonna solve this with deep-learning libraries
like tensorflow or torch

Can i use these libraries or others?

**Comment by ugurkanates** [comment]
Yes of course.

**Comment by JungHY** [comment]
> Yes of course.

Thanks for reply

**Comment by madratman** [comment]
Yes, you can use other libraries to build your solution
